### ISSUE TITLE
Landing Page Design 

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#1]
I think using bootstrap will be the easiest way to do so
The main component of the landing page will be:
1. [ ] position the logo
2. [ ] position the upload form
3. [ ] embed a awesome "BLUE" background picture
4. [ ] etc

For example something like this:
![background](https://cloud.githubusercontent.com/assets/4862905/6043992/4f54d0f2-ac88-11e4-89c5-2b013473cd4b.png)

This website lets us to download all original code for building web template using bootstrap
http://startbootstrap.com/template-categories/all/

**Comment by ghost** [comment]
i'll try this, using the template. what i'm thinking is layering the main interface and landing page on top of each other and then when the user clicks "find out more", switching the visibilities

**Comment by ghost** [comment]
i've added the landing page, link to hide it and a link back. the css is a little inconsistent though cause we're using bits of the template you linked, and bits of the sidebar template.

**Comment by ghost** [comment]
also am I supposed to create a new branch when i make changes?

**Comment by chwangaa** [comment]
> also am I supposed to create a new branch when i make changes?

@andrewwang7 I think it's more maintainable that everyone at this point create a new branch for every component build. For instance, create a branch `landing_page`

>  layering the main interface and landing page on top of each other and then when the user clicks "find out more", switching the visibilities

I think it will add less complexity to extend the enum variable we talked about,
for instance:

``` javascript
            var WINDOW = {
                LANDING: {id: 'page_landing'},
                UPLOAD: {id: 'page_upload'},
                CLOUD: {id: 'page_cloudmap'},
                LIST: {id: 'page_text'}
            }
```

and then in the [html](https://github.com/chwangaa/Charlie/blob/master/main.html#57) under `<div id='views'>`, make another one like:
`<div class='view' id='page_landng'>`

**Comment by chwangaa** [comment]
will be great if u can post screenshots so we can discuss whether it is "BLUE" enough, hahahahaha

Another thing is, do we really need to distinguish **landing page** and **upload page**
I suppose we main reason is like add some intro and bio in the landing page?

**Comment by ghost** [comment]
alright, i'll try and finish switchView while i'm at it

**Comment by ghost** [comment]
for the distinction between landing page and upload page, should we ask the users for keywords at the upload stage?

**Comment by chwangaa** [comment]
I think we indeed should discuss this. Supposable we may also ask for something like:
What is your question?
The answer typed in can be a good heading for diagrams, etc.

Are u saying in the landing page we just ask for file, and then in a **separate upload page** for extra input?

**Comment by chwangaa** [comment]
Andrew, can u post some screenshot pls?

**Comment by ghost** [comment]
ok, i'll post when I have more to show

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10156675/6059770/69047f48-ad2d-11e4-857d-6eb696b7b2f6.png)

To make the file_source input less out of place, i'm trying to hide it and use javascript to link it with a standard link.

The landing page is just the template at the moment

![image](https://cloud.githubusercontent.com/assets/10156675/6059792/9b20d332-ad2d-11e4-9729-db98b9a0de72.png)

**Comment by ghost** [comment]
and they're all views now

**Comment by chwangaa** [comment]
Yeah, make sense. So is it basically get started is a `<a></a>` tag in a separate say `index.html` and that links to the `main.html` right?

I like having labels like "Step 1", "Step 2". Do you think we should divide them into different `views` or keep them together?

@DariaDicu @swarajdash @tanvipotdar @andrewwang7

**Comment by ghost** [comment]
get started switches views to the upload view, and yea it's an a tag

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10156675/6063740/7c6c1c20-ad51-11e4-9acf-cbdc7b3143d1.png)

![image](https://cloud.githubusercontent.com/assets/10156675/6063742/8725bda6-ad51-11e4-919c-23349b265111.png)

**Comment by ghost** [comment]
i'll merge the login page with the landing page somehow, maybe like facebooks

**Comment by ghost** [comment]
pretty simple but it it works 
![image](https://cloud.githubusercontent.com/assets/10156675/6236844/f1260e16-b6e5-11e4-9546-1f632978f3f5.png)
the arrow does a nice scroll thing to
![image](https://cloud.githubusercontent.com/assets/10156675/6236851/018f5cda-b6e6-11e4-984d-e77f5d73c7b7.png)
and i changed the urls, but you might wanna double check if i broke anything else

**Comment by chwangaa** [comment]
The only thing I would say is "AWESOME!"
