### ISSUE TITLE
Dashboard Layout

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#10]
We need to discuss how to display the previously submitted dataset at the dashboard, (each specific user's home page)

I think something icon-like might suit the purpose

![screenshot-joinagora com 2015-02-13 14-45-28](https://cloud.githubusercontent.com/assets/4862905/6189010/25908eec-b38f-11e4-9278-3483e7b33b98.png)

**Comment by ghost** [comment]
progress

![image](https://cloud.githubusercontent.com/assets/10156675/6200557/afdff0ba-b475-11e4-8544-98c253e0f418.png)

**Comment by ghost** [comment]
Cleaned it up, added proper header, added a nicer font. I need help (someone else do it) parsing out the file name, but i'll try and get the delete and add things working. Also, design ideas really appreciated

![image](https://cloud.githubusercontent.com/assets/10156675/6216128/c445e7b4-b5fe-11e4-8acc-9ca54cd2a379.png)

**Comment by chwangaa** [comment]
- was that delibrate blue? Haha
- Project and Charlie are two separate <a> tags
- Problem with the file name being too long. (we need to discuss on what to show I suppose)

**Comment by chwangaa** [comment]
- when "add new" form being prompt, there isn't a way to go back, i.e. Abort creating new form

**Comment by ghost** [comment]
1. yes. 
2. ok i'll fix
3. parse the string, delimit with "/", show fear.csv. i could probably do that too
4. ok, i'll add a cancel

**Comment by ghost** [comment]
i'm not sure if i broke the main page or if you're in the middle of changing it

**Comment by chwangaa** [comment]
I changed welcome user, to the user's specific name
![screenshot-localhost 8000 2015-02-17 13-41-27](https://cloud.githubusercontent.com/assets/4862905/6229030/b9422bf0-b6aa-11e4-9391-6d7aa2ea32e7.png)

**Comment by chwangaa** [comment]
what's up with the main page?

**Comment by ghost** [comment]
sick

**Comment by ghost** [comment]
does it work for you?

**Comment by chwangaa** [comment]
which specific function u mean?

**Comment by ghost** [comment]
theres no cloud, no table. presumably no data is being parsed

**Comment by chwangaa** [comment]
It's working for me, I made another push, try to pull it and see if any problem persist

**Comment by chwangaa** [comment]
There is a subtle css loading error

![screenshot from 2015-02-17 13 52 46](https://cloud.githubusercontent.com/assets/4862905/6229130/4bf3638c-b6ac-11e4-8d27-8010c747c3d6.png)

Although so far I don't see it intervenes with any functional perspective of the page

**Comment by ghost** [comment]
ok

i get this
![image](https://cloud.githubusercontent.com/assets/10156675/6229136/5be59b0c-b6ac-11e4-8794-3798bc509dd0.png)

**Comment by chwangaa** [comment]
Oh, that's probably due to the imcompatibility of our database, delete urs, and run syncdb again

**Comment by ghost** [comment]
yea i tried, happens every time

**Comment by ghost** [comment]
NEVERMIND i figured out the problem
