### ISSUE TITLE
Fix the size of pie-charts

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#11]
Currently the pie-chart automatically renders to the maximum it can be

**Comment by chwangaa** [comment]
@andrewwang7 Andrew, would you mind look into this one as well please?

The bug is that when there is some resizing going on, I think some css might work

And possibly separate the two charts apart.

Ideally, I think having two quite far, and one needs to scroll down to see the other. But the trick is we need to let the user know there is something below again

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10156675/6284234/e16b8b5c-b8e5-11e4-803e-a05c58b80e07.png)
![image](https://cloud.githubusercontent.com/assets/10156675/6284235/e5a3f83a-b8e5-11e4-87d9-62b8d6bc5d9c.png)
![image](https://cloud.githubusercontent.com/assets/10156675/6284238/e9ebdee4-b8e5-11e4-9dc0-ac96e9bdaa83.png)

**Comment by chwangaa** [comment]
Did u change the colour as well?

**Comment by ghost** [comment]
nah the colours are still inconsistent, but thats an "enhancement"

**Comment by chwangaa** [comment]
The two dots needs to go done a little bit to give better "clicking" effect

**Comment by ghost** [comment]
i don't know how to do that so imma just close this
