### ISSUE TITLE
Enable dropdown & collapse of filters

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#15]
The Filter Label, and the `country` and `station` sub-label should ideally be clickable and collapse themselves `.onclick()`

![screenshot-localhost 8000 2015-02-13 14-55-58](https://cloud.githubusercontent.com/assets/4862905/6189187/9bb9a044-b390-11e4-913d-1b36604a5699.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10156675/6258211/9fe9abfa-b7be-11e4-82d3-fd12fa45fd14.png)
![image](https://cloud.githubusercontent.com/assets/10156675/6258214/a9e970c2-b7be-11e4-91c0-9b2805449297.png)

Would be nice to separate country and station filters but I don't know how

I also cleaned up the icons and got rid of unnecessary ones

**Comment by DariaDicu** [comment]
The first country is indented to the right. I think it happens after this change.

**Comment by ghost** [comment]
fixed
![image](https://cloud.githubusercontent.com/assets/10156675/6284272/2bf2ed46-b8e6-11e4-8a42-25718829a607.png)

**Comment by chwangaa** [comment]
If it happens to be only few lines of code, might be nice to dropdown according to country and stations and opinions

**Comment by DariaDicu** [comment]
Oh, Andrew, I think I modified some HTML in the sidebar, so it might be better to merge manually. Hope it doesn't change much. There were some weird tags, like a li for the entire list and then only <br> between lines, instead of wrapping them in something else. I've only seen your changes now :(

**Comment by ghost** [comment]
That's ok, I didn't change much just got rid of an indent
