### ISSUE TITLE
Collect a list of skip words

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#16]
Need a list of following words:
1. [x] abbreviations:
- cos
- gr8
1. [x] names:
2. [ ] stop words:
- and
- because
- porque
1. [ ] common theme
- eya
- ayi

**Comment by swarajdash** [comment]
Abbreviations are words that we essentially do a search-and-replace for when we're 'fixing' the text, and both names and stop words can be considered as one list of words that we ignore, right? (So they can be added to the same list in the implementation, for example.)
What's common theme? Is that what we've been talking about as categories, or keywords that go in categories?

**Comment by chwangaa** [comment]
I think it will be better to provide 'fixing' as a service, instead of assume it and apply automatically.

Therefore, it makes more sense to give the user the options regarding what to apply
