### ISSUE TITLE
Inputs required from users

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#2]
We also need to discuss what kind of inputs shall we ask from users. The things I can think of are:
- What is the Question? (Which disease do you fear the most?)
- What's the data source? (fear.csv)
- What are the available options? (aids, malaria), or possibly something like ([aids, sida, hiv], [malaria, maleria, malara]) which will require a layer of parsing

Also, how shall we phrase these questions and in what order to propose?

Reference to the landing page design Andrew is currently doing: #1

**Comment by swarajdash** [comment]
For Q3 we should just prompt the user to enter the main set of answers that they want to sort their dataset into. In this case it'll be {aids, malaria}. Obviously the 'aids' and 'malaria' are just labels -- not words that we'll search for. It'll be the user that'll see the most frequent words and sort them on their own.

**Comment by swarajdash** [comment]
Also, I don't think we need to have these things as questions, that makes it look unprofessional imho. Just leave it as Andrew's done so far.
