### ISSUE TITLE
Trash

### ISSUE THREAD

**Issue by swarajdash** [chwangaa/Charlie#23]
Implement the functionality of removing the existing data source.

**Comment by DariaDicu** [comment]
Works, but after changing the div to a+span, it doesn't, as the anchor redirects to a different page and there are issues with the AJAX request.

Can we instead "cheat" by adding a ".delete:hover" property in dashboard.css? Works when I tested it :)

**Comment by ghost** [comment]
sorry just saw this. yeah, that sounds good, push it?

**Comment by ghost** [comment]
done

**Comment by DariaDicu** [comment]
oups, saw it too late, but thanks :)

**Comment by DariaDicu** [comment]
Must delete referenced SMSs too!

**Comment by DariaDicu** [comment]
Must delete referenced messages too!
