### ISSUE TITLE
Ways to clean the dataset

### ISSUE THREAD

**Issue by tanvipotdar** [chwangaa/Charlie#27]
- [x] Remove repeated messages
- [ ] Remove messages with a single word
- [x] Delete words of a single letter (?)
- [x] Remove numbers unless part of a 'txt-speak' word e.g. gr8
- [x] Fix up 'txt-speak'
- [ ] Delete non alphabetic characters
- [x] Remove names and replace with [NE](Name Entity)
- [ ] Removing punctuation to leave a list of space seperated words
- [ ] Identify stopwords (e.g., and, for, but) to filter out

**Comment by chwangaa** [comment]
To enable user dynamically modify, and possible change in specs
Might be good that for each function listed, please create a separate def() call.
And then in a wrapper just call all of them
