### ISSUE TITLE
Interface for data manipulation

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#30]
Once Tanvi done with the functions, I think something like this, with a suitable color theme:

![screenshot-localhost 8000 2015-02-18 17-30-02](https://cloud.githubusercontent.com/assets/4862905/6252670/e6428106-b793-11e4-84e2-e8bfb63bd244.png)

**Comment by ghost** [comment]
im going for something like this. i think i'll try and move the forms to appear by drop down menu

![image](https://cloud.githubusercontent.com/assets/10156675/6319281/65cba8c2-baae-11e4-9fbe-156bfd23e67d.png)

**Comment by chwangaa** [comment]
I love the design

**Comment by chwangaa** [comment]
I think the "save change" button needs a bit of speciality

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10156675/6319637/76ceefd2-babb-11e4-8e5f-4c3c20e6b8af.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10156675/6349588/11a62e62-bc24-11e4-8c36-c0c00273a397.png)
![image](https://cloud.githubusercontent.com/assets/10156675/6349591/17f05ed2-bc24-11e4-9a02-f9efaf4405b8.png)

**Comment by chwangaa** [comment]
download should have some speciality, visualize as well, the order is a bit confusing as well. But I don't have any better idea, :D

**Comment by ghost** [comment]
yea agreed

**Comment by chwangaa** [comment]
Possibly think about it as a MS word application? "File", which has save and export, "Edit", which has the other things

**Comment by chwangaa** [comment]
I can forward another variable holding the "last modified time" as an extra <p> tag at some point.
Essentially, we think we don't expect users to modify it tooooooo often

**Comment by ghost** [comment]
i think we should just have it all equal, there are only 5 links and other "hierarchies" would be confusing

![image](https://cloud.githubusercontent.com/assets/10156675/6349766/c39f32c0-bc25-11e4-87d7-3562904055c4.png)

**Comment by chwangaa** [comment]
Yeah, Agreed. I like having "Download File" on the edge

**Comment by chwangaa** [comment]
Possibly put delete Selected inside modifications.
With this design, it encourages user to delete a lot.
We make assumption that the input is relevant, therefore this function shall rarely be used in the first place

**Comment by ghost** [comment]
done

**Comment by chwangaa** [comment]
Another thing I am not sure is whether it will look nice to switch the order of "Modified Text" and "Original Text"? I will do the correction in the table_edit.html, but not sure

In that case all un_modifiable columns in LHS, anything else RHS

**Comment by ghost** [comment]
i think if possible, make modified text into multiple lines and have them the same width
