### ISSUE TITLE
Update Button & Side Button

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#37]

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10156675/6284176/56c0bb12-b8e5-11e4-8e19-39924326ee5b.png)
![image](https://cloud.githubusercontent.com/assets/10156675/6284178/5c7f2b1a-b8e5-11e4-8d4a-8aac33db6b08.png)

**Comment by chwangaa** [comment]
Very pretty

**Comment by ghost** [comment]
now with view switching icons only visible in fullscreen

![image](https://cloud.githubusercontent.com/assets/10156675/6285446/d5a1ef42-b8f3-11e4-854b-18f2b2e571e9.png)

will push when i've tried adding animations

**Comment by chwangaa** [comment]
I think height wise this is awesome, is there any way to make the word
cloud even wider? This way there will be less overlap, and probably we can
show more words. Related to issue #22

**Comment by ghost** [comment]
From what I've seen the word cloud is always square, but I'm not sure

**Comment by chwangaa** [comment]
@DariaDicu could it be non-square?

**Comment by ghost** [comment]
At the moment, the refresh link only reloads the page, but on page load all the check boxes are restored. So it doesnt do anything :p.

**Comment by chwangaa** [comment]
Shall we have the sidebar being closed on default?

**Comment by DariaDicu** [comment]
You can make the canvas itself non square (say WxH = 900x600), but the positioning of the words is square by default. So this means that if you zoom in enough, you will see words filling in the canvas on the entire width, but some words will "fly" out of the canvas on the top and bottom.

**Comment by ghost** [comment]
good enough
