### ISSUE TITLE
dropdown menu

### ISSUE THREAD

**Issue by ghost** [chwangaa/Charlie#63]
![image](https://cloud.githubusercontent.com/assets/10156675/6346475/220d394c-bc08-11e4-95f8-e0469433958d.png)

**Comment by chwangaa** [comment]
I think the names needs a slight change, can't just leave it as skip words, add list or anything creative and more descriptive

**Comment by chwangaa** [comment]
btw, is this the most recent branch version?

**Comment by ghost** [comment]
yeah, i just pushed

**Comment by chwangaa** [comment]
Awesome! dropdown doesnt work inside data_analysis

**Comment by ghost** [comment]
damn, i'll have a look

**Comment by ghost** [comment]
it's hidden behind the page-content-wrapper, which covers everything in fullscreen,  i'll think of something later

**Comment by ghost** [comment]
done
