### ISSUE TITLE
Enable User to adjust the opinion in the table

### ISSUE THREAD

**Issue by chwangaa** [chwangaa/Charlie#9]
Essential we need to achieve something like this:

![screenshot-www datatables net 2015-02-13 14-39-14](https://cloud.githubusercontent.com/assets/4862905/6188920/2e3292da-b38e-11e4-91a0-a7146c15d60d.png)

http://www.datatables.net/examples/api/form.html

**Comment by chwangaa** [comment]
![screenshot-localhost 8000 2015-02-16 17-18-55](https://cloud.githubusercontent.com/assets/4862905/6216338/3207c3a6-b601-11e4-880b-1cf9e18e1786.png)

**Comment by DariaDicu** [comment]
so have you implemented it?

**Comment by chwangaa** [comment]
@DariaDicu 

The layout is complete, the server side is responsive

The missing part is the filter & sorter, Something like the following: 
http://www.datatables.net/examples/api/multi_filter_select.html

I observe that with large table, destroy and then redraw table everytime is time-consuming. DataTable comes with sorter and filters, but it's quite hard to understand the syntax
